### ISSUE TITLE
[SoC2020] A Lightweight Map Engine For L7

### ISSUE THREAD

**Issue by neoddish** [antvis/L7#383]
# 轻量级地图引擎<br>A Lightweight map engine For L7

> What is SoC2020: #384 

## 描述 Description

L7 是蚂蚁金服开源空间数据可视化引擎，专注数据层的可视化表达，目前L7 可视化层必须依赖第三方底图才能使用。L7 自身没有独立的地理坐标系和地图交互，但是 L7 定义了地图服务接口，通过实现该接口你可以扩展第三方地图，也可以自定义地图引擎。

L7 is Ant Financial's open source spatial data visualization engine, focusing on the visual expression of the data. At present, the L7 visualization  must rely on a third-party base map to use. L7 itself does not have an independent geographic coordinate system and map interaction, but L7 defines a map service interface. By implementing this interface, you can extend third-party maps or customize the map engine.

## 目标 Goal

根据 L7 地图服务接口，为 L7 实现独立的地图引擎。让 L7 可视化层无需依赖第三方底图可以独立使用，能够自定义坐标系。

1. 默认支持3857坐标系
1. 支持地图平移, 缩放，旋转， 倾斜等交互。
1. 可以扩展其他坐标系如2000坐标系、局部坐标系等
1. L7 现有可视化层能够在该引擎上运行

According to the L7 map service interface, implement an independent map engine for L7. To enable the L7 visualization layer used independently without relying on a third-party basemap and can customize the coordinate system.

1. Support 3857 geographic coordinate system by default
1. Support map pan, zoom, rotate, pithinteraction
1. Can expand other coordinate systems such as 2000 coordinate system, local coordinate system, etc.
1. L7 existing visualization layer can run on this engine

## 需要技能 Prerequisite Skills

- 前端技术、WebGL等技术栈
- 熟悉WebGIS基本原理

<br>

- JavaScript, Canvas，WebGL and front-end engineering skills;
- Basic theory knowledge of WebGIS.

**Comment by lzxue** [comment]
## Apply Now!
## 2020 Alibaba Summer of Code 介绍
- 中文：[https://developer.aliyun.com/topic/summerofcode2020](https://developer.aliyun.com/topic/summerofcode2020)
- English: [https://www.alibabacloud.com/campaign/summerofcode2020](https://www.alibabacloud.com/campaign/summerofcode2020)

![image](https://user-images.githubusercontent.com/6898060/82862680-d9e4b300-9f52-11ea-8426-1adb6ee60e77.png)

## Timeline⏳

![image](https://user-images.githubusercontent.com/6898060/82862696-e49f4800-9f52-11ea-83e9-b1600411b5fb.png)

## Contact us!

Email Address: aliopensource@alibabacloud.com

**Comment by lzxue** [comment]
> Hello @jiazhewang and @lzxue
> I have worked on map-based web applications before and am interested to work on this. Are there any issues or references to get better understanding.
> 
> Thank you,
> Rohit
Thank you for your attention，you can see this https://github.com/antvis/L7/tree/master/packages/maps/src, L7 need a custom map coordinate system

**Comment by diru1100** [comment]
Hello @lzxue 

> Thank you for your attention，you can see this https://github.com/antvis/L7/tree/master/packages/maps/src, L7 need a custom map coordinate system

Yes, I have seen the code. Currently, L7 uses a 3rd party base map such as MapBox or OSM, etc. 

What I understood from the project is to create a similarly small scale L7 customized map entirely to not depend on any external basemaps.

Also, I have seen that the contribution guideline and other documentation is in Chinese entirely. May I create an issue and translate it into English?

Are there any beginner issues to work on or should I submit my proposal from what I understood in the official site:  https://www.alibabacloud.com/campaign/summerofcode2020 ? 

Thank you,
Rohit Dandamudi

**Comment by jiazhewang** [comment]
> Hello @lzxue
> 
> > Thank you for your attention，you can see this https://github.com/antvis/L7/tree/master/packages/maps/src, L7 need a custom map coordinate system
> 
> Yes, I have seen the code. Currently, L7 uses a 3rd party base map such as MapBox or OSM, etc.
> 
> What I understood from the project is to create a similarly small scale L7 customized map entirely to not depend on any external basemaps.
> 
> Also, I have seen that the contribution guideline and other documentation is in Chinese entirely. May I create an issue and translate it into English?
> 
> Are there any beginner issues to work on or should I submit my proposal from what I understood in the official site: https://www.alibabacloud.com/campaign/summerofcode2020 ?
> 
> Thank you,
> Rohit Dandamudi

We will be very grateful for any contribution to the document!

Please just submit your proposal before the deadline.

THX!

**Comment by diru1100** [comment]
> Please just submit your proposal before the deadline.

Hi @jiazhewang 

I have submitted my proposals, but I am not getting any mail confirming my submission. A notification popped up saying wait for the confirmation mail. I have filled the form twice and now I am getting worried if I submitted properly or not. Kindly look into this and give an update.

Thank you very much.

**Comment by jiazhewang** [comment]
> > Please just submit your proposal before the deadline.
> 
> Hi @jiazhewang
> 
> I have submitted my proposals, but I am not getting any mail confirming my submission. A notification popped up saying wait for the confirmation mail. I have filled the form twice and now I am getting worried if I submitted properly or not. Kindly look into this and give an update.
> 
> Thank you very much.

Hi @diru1100 , 

Your submission has been received. The committee will review it. Thx.

**Comment by diru1100** [comment]
Thank you very much @jiazhewang for your apt response, looking forward to have an amazing experience with you all.

Regards, 
Rohit

**Comment by lzxue** [comment]
> Thank you very much @jiazhewang for your apt response, looking forward to have an amazing experience with you all.
> 
> Regards,
> Rohit

We had reviewed you proposals, there have some quesition should you  think or answer.

1.A key problem to be Implement a geographic coordinate system or a map visualization library？
maybe you are not familiar with l7, but the map is independent， such as leaflet/openlayer/mapbox
2. Can you tell me your understanding of map interaction and WebGL camera？

**Comment by diru1100** [comment]
> 1.A key problem to be Implement a geographic coordinate system or a map visualization library？

The issues I can think are:
- Different map projections and different scales of data.
- Unavailability of data or poor quality data.
- handle data sets that are missing a spatial reference or that have the wrong spatial.
- The transition from one coordinate system to another. (Ex: 3857  to 2000)

> maybe you are not familiar with l7, but the map is independent， such as leaflet/openlayer/mapbox

I see, the map is independent in l7. Only the coordinate system has to be customized and implemented.
 
> 2. Can you tell me your understanding of map interaction and WebGL camera？

- I have done a project on 2-D map interaction as part of the national-level hackathon, we used leaflet and PHP to obtain that.
- Coming to WebGL camera, I implemented basic 3D map for my college where I have used WebGL camera to do internal navigation.

**Comment by diru1100** [comment]
> > 1.A key problem to be Implement a geographic coordinate system or a map visualization library？
> 
> The issues I can think are:
> 
> * Different map projections and different scales of data.
> * Unavailability of data or poor quality data.
> * handle data sets that are missing a spatial reference or that have the wrong spatial.
> * The transition from one coordinate system to another. (Ex: 3857  to 2000)
> 
> > maybe you are not familiar with l7, but the map is independent， such as leaflet/openlayer/mapbox
> 
> I see, the map is independent in l7. Only the coordinate system has to be customized and implemented.
> 
> > 1. Can you tell me your understanding of map interaction and WebGL camera？
> 
> * I have done a project on 2-D map interaction as part of the national-level hackathon, we used leaflet and PHP to obtain that.
> * Coming to WebGL camera, I implemented basic 3D map for my college where I have used WebGL camera to do internal navigation.
> 
> > We had reviewed you proposals, there have some quesition should you think or answer.
> 
> Thank you for spending your valuable time @lzxue, Kindly let me if I am heading in the right direction.

Hello @lzxue 

Can you please give an update on this, when you find the time. As the deadline is approaching soon(7th July).

if I am going in the right direction and what should I focus on? 

I have enough experience and quite confident that I will be able to complete the task within the time period mentioned. 


Thank you,
Rohit Dandamudi

**Comment by diru1100** [comment]
@lzxue 

It seems the proposal wasn't good enough, thank you for reviewing it.
Any feedback would be constructive.

**Comment by jiazhewang** [comment]
Unfortunately, no one's proposal passed the committee's selection. But this issue is still of great concern to us, and we still need help and co-construction in this direction. Interested friends can continue to contact us, although not as an ASoC project, but still a good open source cooperation task.

**Comment by jiazhewang** [comment]
> @lzxue @jiazhewang
> 
> It seems the proposal wasn't good enough, thank you for reviewing it.
> Any feedback would be constructive.

Unfortunately, your proposal was not accepted. This does not mean that your proposal is not good, but the competition is fierce, and other proposals may be more suitable for the corresponding project. Thank you very much for participating in this event.
